/**
 * Autogenerated by Thrift Compiler (0.9.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package cn.edu.pku.ss.serviceorch.thrift;

import org.apache.thrift.scheme.IScheme;
import org.apache.thrift.scheme.SchemeFactory;
import org.apache.thrift.scheme.StandardScheme;

import org.apache.thrift.scheme.TupleScheme;
import org.apache.thrift.protocol.TTupleProtocol;
import org.apache.thrift.protocol.TProtocolException;
import org.apache.thrift.EncodingUtils;
import org.apache.thrift.TException;
import java.util.List;
import java.util.ArrayList;
import java.util.Map;
import java.util.HashMap;
import java.util.EnumMap;
import java.util.Set;
import java.util.HashSet;
import java.util.EnumSet;
import java.util.Collections;
import java.util.BitSet;
import java.nio.ByteBuffer;
import java.util.Arrays;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

public class ServiceOrch {

  public interface Iface {

    public void sendServiceOrch(ServiceOrchRequest serviceOrchRequest) throws org.apache.thrift.TException;

  }

  public interface AsyncIface {

    public void sendServiceOrch(ServiceOrchRequest serviceOrchRequest, org.apache.thrift.async.AsyncMethodCallback<AsyncClient.sendServiceOrch_call> resultHandler) throws org.apache.thrift.TException;

  }

  public static class Client extends org.apache.thrift.TServiceClient implements Iface {
    public static class Factory implements org.apache.thrift.TServiceClientFactory<Client> {
      public Factory() {}
      public Client getClient(org.apache.thrift.protocol.TProtocol prot) {
        return new Client(prot);
      }
      public Client getClient(org.apache.thrift.protocol.TProtocol iprot, org.apache.thrift.protocol.TProtocol oprot) {
        return new Client(iprot, oprot);
      }
    }

    public Client(org.apache.thrift.protocol.TProtocol prot)
    {
      super(prot, prot);
    }

    public Client(org.apache.thrift.protocol.TProtocol iprot, org.apache.thrift.protocol.TProtocol oprot) {
      super(iprot, oprot);
    }

    public void sendServiceOrch(ServiceOrchRequest serviceOrchRequest) throws org.apache.thrift.TException
    {
      send_sendServiceOrch(serviceOrchRequest);
      recv_sendServiceOrch();
    }

    public void send_sendServiceOrch(ServiceOrchRequest serviceOrchRequest) throws org.apache.thrift.TException
    {
      sendServiceOrch_args args = new sendServiceOrch_args();
      args.setServiceOrchRequest(serviceOrchRequest);
      sendBase("sendServiceOrch", args);
    }

    public void recv_sendServiceOrch() throws org.apache.thrift.TException
    {
      sendServiceOrch_result result = new sendServiceOrch_result();
      receiveBase(result, "sendServiceOrch");
      return;
    }

  }
  public static class AsyncClient extends org.apache.thrift.async.TAsyncClient implements AsyncIface {
    public static class Factory implements org.apache.thrift.async.TAsyncClientFactory<AsyncClient> {
      private org.apache.thrift.async.TAsyncClientManager clientManager;
      private org.apache.thrift.protocol.TProtocolFactory protocolFactory;
      public Factory(org.apache.thrift.async.TAsyncClientManager clientManager, org.apache.thrift.protocol.TProtocolFactory protocolFactory) {
        this.clientManager = clientManager;
        this.protocolFactory = protocolFactory;
      }
      public AsyncClient getAsyncClient(org.apache.thrift.transport.TNonblockingTransport transport) {
        return new AsyncClient(protocolFactory, clientManager, transport);
      }
    }

    public AsyncClient(org.apache.thrift.protocol.TProtocolFactory protocolFactory, org.apache.thrift.async.TAsyncClientManager clientManager, org.apache.thrift.transport.TNonblockingTransport transport) {
      super(protocolFactory, clientManager, transport);
    }

    public void sendServiceOrch(ServiceOrchRequest serviceOrchRequest, org.apache.thrift.async.AsyncMethodCallback<sendServiceOrch_call> resultHandler) throws org.apache.thrift.TException {
      checkReady();
      sendServiceOrch_call method_call = new sendServiceOrch_call(serviceOrchRequest, resultHandler, this, ___protocolFactory, ___transport);
      this.___currentMethod = method_call;
      ___manager.call(method_call);
    }

    public static class sendServiceOrch_call extends org.apache.thrift.async.TAsyncMethodCall {
      private ServiceOrchRequest serviceOrchRequest;
      public sendServiceOrch_call(ServiceOrchRequest serviceOrchRequest, org.apache.thrift.async.AsyncMethodCallback<sendServiceOrch_call> resultHandler, org.apache.thrift.async.TAsyncClient client, org.apache.thrift.protocol.TProtocolFactory protocolFactory, org.apache.thrift.transport.TNonblockingTransport transport) throws org.apache.thrift.TException {
        super(client, protocolFactory, transport, resultHandler, false);
        this.serviceOrchRequest = serviceOrchRequest;
      }

      public void write_args(org.apache.thrift.protocol.TProtocol prot) throws org.apache.thrift.TException {
        prot.writeMessageBegin(new org.apache.thrift.protocol.TMessage("sendServiceOrch", org.apache.thrift.protocol.TMessageType.CALL, 0));
        sendServiceOrch_args args = new sendServiceOrch_args();
        args.setServiceOrchRequest(serviceOrchRequest);
        args.write(prot);
        prot.writeMessageEnd();
      }

      public void getResult() throws org.apache.thrift.TException {
        if (getState() != org.apache.thrift.async.TAsyncMethodCall.State.RESPONSE_READ) {
          throw new IllegalStateException("Method call not finished!");
        }
        org.apache.thrift.transport.TMemoryInputTransport memoryTransport = new org.apache.thrift.transport.TMemoryInputTransport(getFrameBuffer().array());
        org.apache.thrift.protocol.TProtocol prot = client.getProtocolFactory().getProtocol(memoryTransport);
        (new Client(prot)).recv_sendServiceOrch();
      }
    }

  }

  public static class Processor<I extends Iface> extends org.apache.thrift.TBaseProcessor<I> implements org.apache.thrift.TProcessor {
    private static final Logger LOGGER = LoggerFactory.getLogger(Processor.class.getName());
    public Processor(I iface) {
      super(iface, getProcessMap(new HashMap<String, org.apache.thrift.ProcessFunction<I, ? extends org.apache.thrift.TBase>>()));
    }

    protected Processor(I iface, Map<String,  org.apache.thrift.ProcessFunction<I, ? extends  org.apache.thrift.TBase>> processMap) {
      super(iface, getProcessMap(processMap));
    }

    private static <I extends Iface> Map<String,  org.apache.thrift.ProcessFunction<I, ? extends  org.apache.thrift.TBase>> getProcessMap(Map<String,  org.apache.thrift.ProcessFunction<I, ? extends  org.apache.thrift.TBase>> processMap) {
      processMap.put("sendServiceOrch", new sendServiceOrch());
      return processMap;
    }

    public static class sendServiceOrch<I extends Iface> extends org.apache.thrift.ProcessFunction<I, sendServiceOrch_args> {
      public sendServiceOrch() {
        super("sendServiceOrch");
      }

      public sendServiceOrch_args getEmptyArgsInstance() {
        return new sendServiceOrch_args();
      }

      protected boolean isOneway() {
        return false;
      }

      public sendServiceOrch_result getResult(I iface, sendServiceOrch_args args) throws org.apache.thrift.TException {
        sendServiceOrch_result result = new sendServiceOrch_result();
        iface.sendServiceOrch(args.serviceOrchRequest);
        return result;
      }
    }

  }

  public static class sendServiceOrch_args implements org.apache.thrift.TBase<sendServiceOrch_args, sendServiceOrch_args._Fields>, java.io.Serializable, Cloneable   {
    private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("sendServiceOrch_args");

    private static final org.apache.thrift.protocol.TField SERVICE_ORCH_REQUEST_FIELD_DESC = new org.apache.thrift.protocol.TField("serviceOrchRequest", org.apache.thrift.protocol.TType.STRUCT, (short)1);

    private static final Map<Class<? extends IScheme>, SchemeFactory> schemes = new HashMap<Class<? extends IScheme>, SchemeFactory>();
    static {
      schemes.put(StandardScheme.class, new sendServiceOrch_argsStandardSchemeFactory());
      schemes.put(TupleScheme.class, new sendServiceOrch_argsTupleSchemeFactory());
    }

    public ServiceOrchRequest serviceOrchRequest; // required

    /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
    public enum _Fields implements org.apache.thrift.TFieldIdEnum {
      SERVICE_ORCH_REQUEST((short)1, "serviceOrchRequest");

      private static final Map<String, _Fields> byName = new HashMap<String, _Fields>();

      static {
        for (_Fields field : EnumSet.allOf(_Fields.class)) {
          byName.put(field.getFieldName(), field);
        }
      }

      /**
       * Find the _Fields constant that matches fieldId, or null if its not found.
       */
      public static _Fields findByThriftId(int fieldId) {
        switch(fieldId) {
          case 1: // SERVICE_ORCH_REQUEST
            return SERVICE_ORCH_REQUEST;
          default:
            return null;
        }
      }

      /**
       * Find the _Fields constant that matches fieldId, throwing an exception
       * if it is not found.
       */
      public static _Fields findByThriftIdOrThrow(int fieldId) {
        _Fields fields = findByThriftId(fieldId);
        if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
        return fields;
      }

      /**
       * Find the _Fields constant that matches name, or null if its not found.
       */
      public static _Fields findByName(String name) {
        return byName.get(name);
      }

      private final short _thriftId;
      private final String _fieldName;

      _Fields(short thriftId, String fieldName) {
        _thriftId = thriftId;
        _fieldName = fieldName;
      }

      public short getThriftFieldId() {
        return _thriftId;
      }

      public String getFieldName() {
        return _fieldName;
      }
    }

    // isset id assignments
    public static final Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
    static {
      Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
      tmpMap.put(_Fields.SERVICE_ORCH_REQUEST, new org.apache.thrift.meta_data.FieldMetaData("serviceOrchRequest", org.apache.thrift.TFieldRequirementType.DEFAULT, 
          new org.apache.thrift.meta_data.StructMetaData(org.apache.thrift.protocol.TType.STRUCT, ServiceOrchRequest.class)));
      metaDataMap = Collections.unmodifiableMap(tmpMap);
      org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(sendServiceOrch_args.class, metaDataMap);
    }

    public sendServiceOrch_args() {
    }

    public sendServiceOrch_args(
      ServiceOrchRequest serviceOrchRequest)
    {
      this();
      this.serviceOrchRequest = serviceOrchRequest;
    }

    /**
     * Performs a deep copy on <i>other</i>.
     */
    public sendServiceOrch_args(sendServiceOrch_args other) {
      if (other.isSetServiceOrchRequest()) {
        this.serviceOrchRequest = new ServiceOrchRequest(other.serviceOrchRequest);
      }
    }

    public sendServiceOrch_args deepCopy() {
      return new sendServiceOrch_args(this);
    }

    @Override
    public void clear() {
      this.serviceOrchRequest = null;
    }

    public ServiceOrchRequest getServiceOrchRequest() {
      return this.serviceOrchRequest;
    }

    public sendServiceOrch_args setServiceOrchRequest(ServiceOrchRequest serviceOrchRequest) {
      this.serviceOrchRequest = serviceOrchRequest;
      return this;
    }

    public void unsetServiceOrchRequest() {
      this.serviceOrchRequest = null;
    }

    /** Returns true if field serviceOrchRequest is set (has been assigned a value) and false otherwise */
    public boolean isSetServiceOrchRequest() {
      return this.serviceOrchRequest != null;
    }

    public void setServiceOrchRequestIsSet(boolean value) {
      if (!value) {
        this.serviceOrchRequest = null;
      }
    }

    public void setFieldValue(_Fields field, Object value) {
      switch (field) {
      case SERVICE_ORCH_REQUEST:
        if (value == null) {
          unsetServiceOrchRequest();
        } else {
          setServiceOrchRequest((ServiceOrchRequest)value);
        }
        break;

      }
    }

    public Object getFieldValue(_Fields field) {
      switch (field) {
      case SERVICE_ORCH_REQUEST:
        return getServiceOrchRequest();

      }
      throw new IllegalStateException();
    }

    /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
    public boolean isSet(_Fields field) {
      if (field == null) {
        throw new IllegalArgumentException();
      }

      switch (field) {
      case SERVICE_ORCH_REQUEST:
        return isSetServiceOrchRequest();
      }
      throw new IllegalStateException();
    }

    @Override
    public boolean equals(Object that) {
      if (that == null)
        return false;
      if (that instanceof sendServiceOrch_args)
        return this.equals((sendServiceOrch_args)that);
      return false;
    }

    public boolean equals(sendServiceOrch_args that) {
      if (that == null)
        return false;

      boolean this_present_serviceOrchRequest = true && this.isSetServiceOrchRequest();
      boolean that_present_serviceOrchRequest = true && that.isSetServiceOrchRequest();
      if (this_present_serviceOrchRequest || that_present_serviceOrchRequest) {
        if (!(this_present_serviceOrchRequest && that_present_serviceOrchRequest))
          return false;
        if (!this.serviceOrchRequest.equals(that.serviceOrchRequest))
          return false;
      }

      return true;
    }

    @Override
    public int hashCode() {
      return 0;
    }

    public int compareTo(sendServiceOrch_args other) {
      if (!getClass().equals(other.getClass())) {
        return getClass().getName().compareTo(other.getClass().getName());
      }

      int lastComparison = 0;
      sendServiceOrch_args typedOther = (sendServiceOrch_args)other;

      lastComparison = Boolean.valueOf(isSetServiceOrchRequest()).compareTo(typedOther.isSetServiceOrchRequest());
      if (lastComparison != 0) {
        return lastComparison;
      }
      if (isSetServiceOrchRequest()) {
        lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.serviceOrchRequest, typedOther.serviceOrchRequest);
        if (lastComparison != 0) {
          return lastComparison;
        }
      }
      return 0;
    }

    public _Fields fieldForId(int fieldId) {
      return _Fields.findByThriftId(fieldId);
    }

    public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
      schemes.get(iprot.getScheme()).getScheme().read(iprot, this);
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
      schemes.get(oprot.getScheme()).getScheme().write(oprot, this);
    }

    @Override
    public String toString() {
      StringBuilder sb = new StringBuilder("sendServiceOrch_args(");
      boolean first = true;

      sb.append("serviceOrchRequest:");
      if (this.serviceOrchRequest == null) {
        sb.append("null");
      } else {
        sb.append(this.serviceOrchRequest);
      }
      first = false;
      sb.append(")");
      return sb.toString();
    }

    public void validate() throws org.apache.thrift.TException {
      // check for required fields
      // check for sub-struct validity
      if (serviceOrchRequest != null) {
        serviceOrchRequest.validate();
      }
    }

    private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
      try {
        write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
      } catch (org.apache.thrift.TException te) {
        throw new java.io.IOException(te);
      }
    }

    private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, ClassNotFoundException {
      try {
        read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
      } catch (org.apache.thrift.TException te) {
        throw new java.io.IOException(te);
      }
    }

    private static class sendServiceOrch_argsStandardSchemeFactory implements SchemeFactory {
      public sendServiceOrch_argsStandardScheme getScheme() {
        return new sendServiceOrch_argsStandardScheme();
      }
    }

    private static class sendServiceOrch_argsStandardScheme extends StandardScheme<sendServiceOrch_args> {

      public void read(org.apache.thrift.protocol.TProtocol iprot, sendServiceOrch_args struct) throws org.apache.thrift.TException {
        org.apache.thrift.protocol.TField schemeField;
        iprot.readStructBegin();
        while (true)
        {
          schemeField = iprot.readFieldBegin();
          if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
            break;
          }
          switch (schemeField.id) {
            case 1: // SERVICE_ORCH_REQUEST
              if (schemeField.type == org.apache.thrift.protocol.TType.STRUCT) {
                struct.serviceOrchRequest = new ServiceOrchRequest();
                struct.serviceOrchRequest.read(iprot);
                struct.setServiceOrchRequestIsSet(true);
              } else { 
                org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
              }
              break;
            default:
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
          }
          iprot.readFieldEnd();
        }
        iprot.readStructEnd();

        // check for required fields of primitive type, which can't be checked in the validate method
        struct.validate();
      }

      public void write(org.apache.thrift.protocol.TProtocol oprot, sendServiceOrch_args struct) throws org.apache.thrift.TException {
        struct.validate();

        oprot.writeStructBegin(STRUCT_DESC);
        if (struct.serviceOrchRequest != null) {
          oprot.writeFieldBegin(SERVICE_ORCH_REQUEST_FIELD_DESC);
          struct.serviceOrchRequest.write(oprot);
          oprot.writeFieldEnd();
        }
        oprot.writeFieldStop();
        oprot.writeStructEnd();
      }

    }

    private static class sendServiceOrch_argsTupleSchemeFactory implements SchemeFactory {
      public sendServiceOrch_argsTupleScheme getScheme() {
        return new sendServiceOrch_argsTupleScheme();
      }
    }

    private static class sendServiceOrch_argsTupleScheme extends TupleScheme<sendServiceOrch_args> {

      @Override
      public void write(org.apache.thrift.protocol.TProtocol prot, sendServiceOrch_args struct) throws org.apache.thrift.TException {
        TTupleProtocol oprot = (TTupleProtocol) prot;
        BitSet optionals = new BitSet();
        if (struct.isSetServiceOrchRequest()) {
          optionals.set(0);
        }
        oprot.writeBitSet(optionals, 1);
        if (struct.isSetServiceOrchRequest()) {
          struct.serviceOrchRequest.write(oprot);
        }
      }

      @Override
      public void read(org.apache.thrift.protocol.TProtocol prot, sendServiceOrch_args struct) throws org.apache.thrift.TException {
        TTupleProtocol iprot = (TTupleProtocol) prot;
        BitSet incoming = iprot.readBitSet(1);
        if (incoming.get(0)) {
          struct.serviceOrchRequest = new ServiceOrchRequest();
          struct.serviceOrchRequest.read(iprot);
          struct.setServiceOrchRequestIsSet(true);
        }
      }
    }

  }

  public static class sendServiceOrch_result implements org.apache.thrift.TBase<sendServiceOrch_result, sendServiceOrch_result._Fields>, java.io.Serializable, Cloneable   {
    private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("sendServiceOrch_result");


    private static final Map<Class<? extends IScheme>, SchemeFactory> schemes = new HashMap<Class<? extends IScheme>, SchemeFactory>();
    static {
      schemes.put(StandardScheme.class, new sendServiceOrch_resultStandardSchemeFactory());
      schemes.put(TupleScheme.class, new sendServiceOrch_resultTupleSchemeFactory());
    }


    /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
    public enum _Fields implements org.apache.thrift.TFieldIdEnum {
;

      private static final Map<String, _Fields> byName = new HashMap<String, _Fields>();

      static {
        for (_Fields field : EnumSet.allOf(_Fields.class)) {
          byName.put(field.getFieldName(), field);
        }
      }

      /**
       * Find the _Fields constant that matches fieldId, or null if its not found.
       */
      public static _Fields findByThriftId(int fieldId) {
        switch(fieldId) {
          default:
            return null;
        }
      }

      /**
       * Find the _Fields constant that matches fieldId, throwing an exception
       * if it is not found.
       */
      public static _Fields findByThriftIdOrThrow(int fieldId) {
        _Fields fields = findByThriftId(fieldId);
        if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
        return fields;
      }

      /**
       * Find the _Fields constant that matches name, or null if its not found.
       */
      public static _Fields findByName(String name) {
        return byName.get(name);
      }

      private final short _thriftId;
      private final String _fieldName;

      _Fields(short thriftId, String fieldName) {
        _thriftId = thriftId;
        _fieldName = fieldName;
      }

      public short getThriftFieldId() {
        return _thriftId;
      }

      public String getFieldName() {
        return _fieldName;
      }
    }
    public static final Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
    static {
      Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
      metaDataMap = Collections.unmodifiableMap(tmpMap);
      org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(sendServiceOrch_result.class, metaDataMap);
    }

    public sendServiceOrch_result() {
    }

    /**
     * Performs a deep copy on <i>other</i>.
     */
    public sendServiceOrch_result(sendServiceOrch_result other) {
    }

    public sendServiceOrch_result deepCopy() {
      return new sendServiceOrch_result(this);
    }

    @Override
    public void clear() {
    }

    public void setFieldValue(_Fields field, Object value) {
      switch (field) {
      }
    }

    public Object getFieldValue(_Fields field) {
      switch (field) {
      }
      throw new IllegalStateException();
    }

    /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
    public boolean isSet(_Fields field) {
      if (field == null) {
        throw new IllegalArgumentException();
      }

      switch (field) {
      }
      throw new IllegalStateException();
    }

    @Override
    public boolean equals(Object that) {
      if (that == null)
        return false;
      if (that instanceof sendServiceOrch_result)
        return this.equals((sendServiceOrch_result)that);
      return false;
    }

    public boolean equals(sendServiceOrch_result that) {
      if (that == null)
        return false;

      return true;
    }

    @Override
    public int hashCode() {
      return 0;
    }

    public int compareTo(sendServiceOrch_result other) {
      if (!getClass().equals(other.getClass())) {
        return getClass().getName().compareTo(other.getClass().getName());
      }

      int lastComparison = 0;
      sendServiceOrch_result typedOther = (sendServiceOrch_result)other;

      return 0;
    }

    public _Fields fieldForId(int fieldId) {
      return _Fields.findByThriftId(fieldId);
    }

    public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
      schemes.get(iprot.getScheme()).getScheme().read(iprot, this);
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
      schemes.get(oprot.getScheme()).getScheme().write(oprot, this);
      }

    @Override
    public String toString() {
      StringBuilder sb = new StringBuilder("sendServiceOrch_result(");
      boolean first = true;

      sb.append(")");
      return sb.toString();
    }

    public void validate() throws org.apache.thrift.TException {
      // check for required fields
      // check for sub-struct validity
    }

    private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
      try {
        write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
      } catch (org.apache.thrift.TException te) {
        throw new java.io.IOException(te);
      }
    }

    private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, ClassNotFoundException {
      try {
        read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
      } catch (org.apache.thrift.TException te) {
        throw new java.io.IOException(te);
      }
    }

    private static class sendServiceOrch_resultStandardSchemeFactory implements SchemeFactory {
      public sendServiceOrch_resultStandardScheme getScheme() {
        return new sendServiceOrch_resultStandardScheme();
      }
    }

    private static class sendServiceOrch_resultStandardScheme extends StandardScheme<sendServiceOrch_result> {

      public void read(org.apache.thrift.protocol.TProtocol iprot, sendServiceOrch_result struct) throws org.apache.thrift.TException {
        org.apache.thrift.protocol.TField schemeField;
        iprot.readStructBegin();
        while (true)
        {
          schemeField = iprot.readFieldBegin();
          if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
            break;
          }
          switch (schemeField.id) {
            default:
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
          }
          iprot.readFieldEnd();
        }
        iprot.readStructEnd();

        // check for required fields of primitive type, which can't be checked in the validate method
        struct.validate();
      }

      public void write(org.apache.thrift.protocol.TProtocol oprot, sendServiceOrch_result struct) throws org.apache.thrift.TException {
        struct.validate();

        oprot.writeStructBegin(STRUCT_DESC);
        oprot.writeFieldStop();
        oprot.writeStructEnd();
      }

    }

    private static class sendServiceOrch_resultTupleSchemeFactory implements SchemeFactory {
      public sendServiceOrch_resultTupleScheme getScheme() {
        return new sendServiceOrch_resultTupleScheme();
      }
    }

    private static class sendServiceOrch_resultTupleScheme extends TupleScheme<sendServiceOrch_result> {

      @Override
      public void write(org.apache.thrift.protocol.TProtocol prot, sendServiceOrch_result struct) throws org.apache.thrift.TException {
        TTupleProtocol oprot = (TTupleProtocol) prot;
      }

      @Override
      public void read(org.apache.thrift.protocol.TProtocol prot, sendServiceOrch_result struct) throws org.apache.thrift.TException {
        TTupleProtocol iprot = (TTupleProtocol) prot;
      }
    }

  }

}
